name: 'Terraform'

on:
  push:
    branches:
      - 'feat/provision-aws-rds'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v1

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve
      - name: 'Execute SQL script'
        run: |
          mysql --host=<your-db-host> --user=<your-db-user> --password=<your-db-password> --database=<your-db-name> < scripts/your-script.sql