name: 'Terraform'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'feat/provision-aws-rds'
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        id: apply
        run: terraform apply -auto-approve
    
      - name: 'Set RDS Address as Env Var'
        run: echo "RDS_ADDRESS=$(terraform output -raw rds_address)" >> $GITHUB_ENV
        
      - name: 'Execute SQL script'
        run: |
          mysql --host=${{  env.RDS_ADDRESS }} -P 3306 --user=${{env.MYSQL_USER}} --password=${{secrets.MYSQL_PASSWORD}} --database=${{env.MYSQL_DBNAME}}  --protocol=TCP < scripts/migration_prod.sql

      - name: 'Terraform Destroy'
        run: terraform destroy -auto-approve
        