name: 'Terraform'

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'feat/provision-aws-rds'
permissions:
  id-token: write
  contents: read
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve

      - name: 'Get RDS endpoint'
        id: rds
        run: echo "::set-output name=endpoint::$(terraform output -raw rds_endpoint)"
        
      - name: 'Execute SQL script'
        run: |
          mysql --host=${{ steps.rds.output.endpoint }} --user=${{env.MYSQL_USER}} --password=${{secrets.MYSQL_PASSWORD}} -P ${{env.MYSQL_PORT}} --database=${{env.MYSQL_DBNAME}} < scripts/migration_prod.sql
          - name: Terraform Destroy
      - name: 'Terraform Destroy'
        run: terraform destroy -auto-approve
        